# Generated by Django 4.1.2 on 2023-06-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='PetShop')),
            ],
        ),
    ]
