# Generated by Django 4.1.2 on 2023-06-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0003_alter_mascota_esterilizado_alter_mascota_vacunas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(),
        ),
    ]
