# Generated by Django 4.1.2 on 2023-06-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0004_alter_mascota_esterilizado_alter_mascota_vacunas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
    ]
