# Generated by Django 4.1.2 on 2023-06-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0005_alter_mascota_esterilizado_alter_mascota_vacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('nro_telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(),
        ),
    ]
