# Generated by Django 4.1.2 on 2023-06-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0006_mensaje_alter_mascota_esterilizado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensaje',
        ),
    ]
