# Generated by Django 4.1.2 on 2023-06-29 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0008_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensaje',
        ),
    ]
