# Generated by Django 4.1.2 on 2023-06-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0011_fundacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fundacion',
        ),
    ]
