# Generated by Django 4.1.2 on 2023-06-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0013_fundacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='solicitud',
        ),
    ]
